const fixtures = [
  {
    id: '1',
    date: 'Lördag 3 November',
    place: 'GA-Hallens, HBG',
    home: 'Team4Q',
    vs: 'vs',
    away: 'Högsbo',
    time: false,
    result: '101-110',
    status: 'lose',
    info: 'Important info !!',
  },
  {
    id: '2',
    date: 'Lördag 10 November',
    place: 'Eoshallen, Lund',
    home: 'IK EOS',
    vs: 'vs',
    away: 'Team4Q',
    time: false,
    result: '127-104',
    status: 'lose',
    info: 'some text',
  },
  {
    id: '3',
    date: 'Lördag 31 November',
    place: 'GA-Hallens, HBG',
    home: 'Team4Q',
    vs: 'vs',
    away: 'Uppsala',
    time: false,
    result: '86-90',
    status: 'lose',
    info: 'some text',
  },
  {
    id: '4',
    date: 'Postponed',
    place: '',
    home: 'Team4Q',
    vs: 'vs',
    away: 'Wetterbygden',
    time: 'Postponed',
    result: '',
    status: '',
    info: 'some text',
  },
  {
    id: '5',
    date: 'Postponed',
    place: '',
    home: 'norrort',
    vs: 'vs',
    away: 'team4q',
    time: 'Postponed',
    result: '',
    status: '',
    info: 'some text',
  },
  {
    id: '6',
    date: 'Postponed',
    place: '',
    home: 'ockelbo',
    vs: 'vs',
    away: 'team4q',
    time: 'Postponed',
    result: '',
    status: '',
    info: 'some text',
  },
  {
    id: '7',
    date: 'Lördag 21 November',
    place: 'Kinnahallen',
    home: 'RIG Mark',
    vs: 'vs',
    away: 'team4q',
    time: '13:00',
    result: '',
    status: '',
    info: 'some text',
  },
  {
    id: '8',
    date: 'Lördag 28 November',
    place: 'Huskvarna Sporthall',
    home: 'wetterbygden',
    vs: 'vs',
    away: 'team4q',
    time: '15:00',
    result: '',
    status: '',
    info: 'some text',
  },
  {
    id: '9',
    date: 'Lördag 5 December',
    place: 'GA-Hallen, HBG',
    home: 'team4q',
    vs: 'vs',
    away: 'trelleborg',
    time: '15:00',
    result: '',
    status: '',
    info: 'some text',
  },
  {
    id: '10',
    date: 'Lördag 12 December',
    place: 'Vasalundshallen',
    home: 'aik',
    vs: 'vs',
    away: 'team4q',
    time: '16:30',
    result: '',
    status: '',
    info: 'some text',
  },
  {
    id: '11',
    date: 'Lördag 19 December',
    place: 'GA-Hallen, HBG',
    home: 'team4q',
    vs: 'vs',
    away: 'alvik',
    time: '15:00',
    result: '',
    status: '',
    info: 'some text',
  },
  {
    id: '12',
    // date: 'Lördag 9 Januari',
    date: 'Sat Jan 09 2021',
    place: 'Gothia Arena 2',
    home: 'högsbo',
    vs: 'vs',
    away: 'team4q',
    time: '15:30',
    result: '',
    status: '',
    info: 'some text',
  },
  {
    id: '13',
    // date: 'Söndag 17 Januari',
    date: 'Sun Jan 17 2021',
    place: 'GA-Hallen, HBG',
    home: 'team4q',
    vs: 'vs',
    away: 'IK EOS',
    time: '15:00',
    result: '',
    status: '',
    info: 'some text',
  },
  {
    id: '14',
    // date: 'Lördag 23 Januari',
    date: 'Sat Jan 23 2021',
    place: 'Sportcenter A, Kalmar',
    home: 'kalmar',
    vs: 'vs',
    away: 'team4q',
    time: '15:00',
    result: '',
    status: '',
    info: 'some text',
  },
  {
    id: '15',
    // date: 'Söndag 31 Januari',
    date: 'Sun Jan 31 2021',
    place: 'GA-Hallen, HBG',
    home: 'team4q',
    vs: 'vs',
    away: 'kalmar',
    time: '13:00',
    result: '',
    status: '',
    info: 'some text',
  },
  {
    id: '16',
    // date: 'Söndag 7 Februari',
    date: 'Sun Feb 07 2021',
    place: 'Upplands Bilforum USIF Arena',
    home: 'uppsala',
    vs: 'vs',
    away: 'team4q',
    time: '16:00',
    result: '',
    status: '',
    info: 'some text',
  },
  {
    id: '17',
    // date: 'Lördag 13 Februari',
    date: 'Sat Feb 13 2021',
    place: 'GA-Hallen, HBG',
    home: 'team4q',
    vs: 'vs',
    away: 'norrort',
    time: '15:00',
    result: '',
    status: '',
    info: 'some text',
  },
  {
    id: '18',
    // date: 'Lördag 20 Februari',
    date: 'Sat Feb 20 2021',
    place: 'kuxahallen',
    home: 'ockelbo',
    vs: 'vs',
    away: 'team4q',
    time: '16:00',
    result: '',
    status: '',
    info: 'some text',
  },
  {
    id: '19',
    // date: 'Lördag 27 Februari',
    date: 'Sat Feb 27 2021',
    place: 'GA-Hallen',
    home: 'team4q',
    vs: 'vs',
    away: 'RIG Mark',
    time: '15:00',
    result: '',
    status: '',
    info: 'some text',
  },
  {
    id: '20',
    // date: 'Lördag 6 Mars',
    date: 'Sat May 06 2021',
    place: 'Åkeshovshallen',
    home: 'alvik',
    vs: 'vs',
    away: 'team4q',
    time: '14:00',
    result: '',
    status: '',
    info: 'some text',
  },
  {
    id: '21',
    // date: 'Lördag 13 Mars',
    date: 'Sat May 13 2021',
    place: 'Västervångshallen',
    home: 'trelleborg',
    vs: 'vs',
    away: 'team4q',
    time: '15:00',
    result: '',
    status: '',
    info: 'some text',
  },
  {
    id: '22',
    // date: 'Lördag 13 Mars',
    date: 'Sat May 23 2021',
    place: 'GA-Hallen, HBG',
    home: 'team4q',
    vs: 'vs',
    away: 'aik',
    time: '11:30',
    result: '',
    status: '',
    info: 'some text',
  },
];

export default fixtures;
